language: python
dist: xenial
python:
  - 3.6
install:
  - pip install -U setuptools
  - pip install -r requirements.txt
script:
  - cd src
  - flake8 . --exclude __init__.py,__pycache__ --max-line-length=100
  - timeout 10s isort
  - python3.6 -m unittest discover tests