language: python
dist: precise
python:
  - 3.7
install:
  - pip install -U setuptools
  - pip install -r requirements.txt
script:
  - cd src
  - flake8 . --exclude __init__.py,__pycache__ --max-line-length=100
  - timeout 10s isort
  - python3.7 -m unittest discover tests